---
- hosts: all
  gather_facts: True
  sudo: True
  roles:
    - marklee77.docker

- hosts: all
  gather_facts: True
  sudo: True
  tasks:

    - name: ensure that login user is in the docker group
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes
        state: present

    #- name: ensure that pip is installed
    #  shell: curl -s https://bootstrap.pypa.io/get-pip.py | python -
    #         creates=/usr/local/bin/pip

    - name: ensure that pip packages are installed
        apt:
          pkg: "{{ item }}"
          state: latest
          update_cache: yes
          cache_valid_time: 600
        with_items:
          - python-dev
          - python-pip

    - name: ensure docker client libraries are installed
      pip:
        name: docker-py
        state: latest
