---
- name: ensure rabbitmq packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - rabbitmq-server

#- name: ensure mariadb does not bind to localhost if remote connections are enabled
#  lineinfile:
#    dest: /etc/mysql/my.cnf
#    regexp: ^bind-address\s*=\s*127.0.0.1
#    line: bind-address = 127.0.0.1
#    insertafter: "\\[mysqld\\]"
#    state: "{% if mariadb_enable_remote %}absent{% else %}present{% endif %}"
#  notify:
#    - restart mariadb

- name: ensure rabbitmq-server is started and enabled
  service: 
    name: rabbitmq-server
    state: started 
    enabled: yes

- name: ensure anonymous guest user is absent
  rabbitmq_user:
    user: guest
    state: absent

- include: setrootpw.yml
  when: rabbitmq_set_root_password
